{{ if .Values.secret.enable }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.secret.name }}
    name: {{ .Values.secret.name }}
  {{- else }}
    name: {{ .Release.Name }}-secret
  {{- end }}
data:
  SLACK_TOKEN: {{ .Values.secret.values.SLACK_TOKEN }}
  SLACK_CHANNEL: {{ .Values.secret.values.SLACK_CHANNEL }}
type: Opaque
{{- end }}