apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
data:
  config.yaml: |-
    repos:
    {{- range $name, $repo := .Values.configmap.repos }}
      - {{ . | toYaml | indent 4 | trim }}
    {{- end }}