{{ if and .Values.secret.enable (eq .Values.secret.type "slack") }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.secret.name }}
    name: {{ .Values.secret.name }}
  {{- else }}
    name: {{ .Release.Name }}-secret
  {{- end }}
data:
  SLACK_TOKEN: {{ .Values.secret.values.SLACK_TOKEN }}
  SLACK_CHANNEL: {{ .Values.secret.values.SLACK_CHANNEL }}
type: Opaque
{{ else if and .Values.secret.enable (eq .Values.secret.type "telegram") }}
apiVersion: v1
kind: Secret
metadata:
  {{- if .Values.secret.name }}
  name: {{ .Values.secret.name }}
  {{- else }}
  name: {{ .Release.Name }}-secret
  {{- end }}
data:
  TELEGRAM_TOKEN: {{ .Values.secret.values.SLACK_TOKEN }}
  TELEGRAM_CHAT_ID: {{ .Values.secret.values.SLACK_CHANNEL }}
type: Opaque
{{- end }}