repos:
  - confluentinc: terraform-provider-confluent
  - hashicorp: terraform-provider-aws
  - hashicorp: terraform-provider-google
  - MuhammedKalkan: OpenLens
  - open-metadata: openmetadata-helm-charts
  - golang: go