name: Chart Release

on:
  push:
    branches:
      - main
    paths:
      - charts/**

jobs:
  chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install

  release:
    runs-on: ubuntu-latest
    needs: chart-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@gmail.com"

      - name: Get Latest Tag
        id: previous_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      
      - name: Configure yq
        uses: mikefarah/yq@v4.30.1

      - name: Get Current Helm Chart Version
        id: helm_version
        run: |
          echo "helmVer=$(yq '.version' charts/version-notifier/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: Turn Helm Version To Timestamp Format
        id: helm_version_timestamp
        uses: mad9000/actions-find-and-replace-string@2
        with:
            source: ${{ steps.helm_version.outputs.helmVer }}
            find: '.'      
            replace: ''

      - name: test
        run: |
          echo "${{ steps.helm_version_timestamp.outputs.value }} ${{ steps.previous_tag.outputs.timestamp }}"

      - name: Bump Version
        uses: actions-ecosystem/action-bump-semver@v1
        id: new_helm_version
        if: steps.previous_tag.outputs.timestamp > steps.helm_version_timestamp.outputs.value
        with:
          current_version: ${{ steps.helm_version.outputs.helmVer }}
          level: patch

      - name: Edit version attributes of the helm chart
        if: steps.previous_tag.outputs.timestamp > steps.helm_version_timestamp.outputs.value
        run: |
          yq -i '.version = "${{ steps.new_helm_version.outputs.new_version }}"' charts/version-notifier/Chart.yaml

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: charts/version-notifier/